# Generated by Django 5.0.3 on 2024-03-27 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('trip_type', models.CharField(choices=[('OW', 'One Way'), ('RT', 'Round Trip')], default='OW', max_length=2)),
                ('status', models.CharField(choices=[('CNL', 'Canceled'), ('PPD', 'Postponed'), ('CMP', 'Completed')], default='CMP', max_length=3)),
                ('outbound_flight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_bookings', to='flights.flight')),
                ('return_flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_bookings', to='flights.flight')),
                ('seat_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flightseatclass')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
