# Generated by Django 5.0.3 on 2024-03-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='flight_id',
            new_name='flight',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('CNL', 'Canceled'), ('PPD', 'Postponed'), ('CMP', 'Completed')], default='CMP', max_length=20),
        ),
    ]
