# Generated by Django 5.0.3 on 2024-03-14 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_id', models.IntegerField()),
                ('airline_name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='airline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.airline'),
        ),
    ]
