# Generated by Django 5.0.3 on 2024-03-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_policy_remove_airline_airline_id_remove_flight_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='policy_id',
            field=models.IntegerField(default=1),
        ),
    ]
