# Generated by Django 5.0.3 on 2024-03-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_alter_policy_policy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='policy_id',
            field=models.IntegerField(),
        ),
    ]
