# Generated by Django 5.0.3 on 2024-03-14 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_alter_policy_policy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='policy_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.policy'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_id',
            field=models.IntegerField(default=1),
        ),
    ]
