# Generated by Django 5.0.3 on 2024-03-21 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0009_airline_airline_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='departure_city',
            field=models.CharField(default='unknow', max_length=100),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_country',
            field=models.CharField(default='unknow', max_length=100),
        ),
        migrations.AddField(
            model_name='flight',
            name='destination_city',
            field=models.CharField(default='unknow', max_length=100),
        ),
        migrations.AddField(
            model_name='flight',
            name='destination_country',
            field=models.CharField(default='unknow', max_length=100),
        ),
        migrations.CreateModel(
            name='FlightSeatClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats_type', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('capacity', models.IntegerField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flight')),
            ],
        ),
    ]
