# Generated by Django 5.0.3 on 2024-03-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0010_flight_departure_city_flight_departure_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightseatclass',
            name='seats_type',
            field=models.CharField(max_length=20),
        ),
    ]
