# Generated by Django 5.0.3 on 2024-03-24 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0012_remove_flight_flight_id_flight_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='dateTime',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
