# Generated by Django 5.0.3 on 2024-03-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0013_alter_flight_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airport_id', models.AutoField(primary_key=True, serialize=False)),
                ('airport_name', models.CharField(max_length=100)),
                ('IATA_code', models.CharField(max_length=3)),
                ('contact_info', models.TextField()),
                ('country', models.CharField(max_length=50)),
            ],
        ),
    ]
