# Generated by Django 5.0.3 on 2024-03-26 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0016_flight_return_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='airportArrival',
            new_name='arrival_airport',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='airportDeparture',
            new_name='departure_airport',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='dateTime',
            new_name='departure_date',
        ),
    ]
