# Generated by Django 5.0.3 on 2024-03-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0017_rename_airportarrival_flight_arrival_airport_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='arrival_airport',
            new_name='airportArrival',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='departure_airport',
            new_name='airportDeparture',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='airline',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='total_rate',
        ),
        migrations.AddField(
            model_name='flight',
            name='ratings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_city',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination_city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='flight',
            name='destination_country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='flight',
            name='notes',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
