# Generated by Django 5.0.3 on 2024-03-06 09:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_id', models.IntegerField(max_length=10)),
                ('dateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('airportDeparture', models.CharField(max_length=40)),
                ('airportArrival', models.CharField(max_length=40)),
                ('notes', models.TextField(max_length=200)),
                ('total_rate', models.IntegerField(default=0)),
                ('id_airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.airline')),
            ],
        ),
        migrations.CreateModel(
            name='FlightSeatClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats_type', models.IntegerField()),
                ('price', models.FloatField(max_length=100)),
                ('count', models.IntegerField(max_length=100)),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.flight')),
            ],
        ),
    ]
