# Generated by Django 5.0.3 on 2024-03-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_alter_flight_flight_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightseatclass',
            name='count',
            field=models.IntegerField(),
        ),
    ]
