# Generated by Django 5.0.3 on 2024-03-06 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_review'),
        ('flight', '0003_alter_flightseatclass_count'),
    ]

    operations = [
    ]
