# Generated by Django 5.0.3 on 2024-03-06 09:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.IntegerField(max_length=10)),
                ('refundable', models.BooleanField(default=False)),
                ('exchangeable', models.BooleanField(default=False)),
                ('exchangeable_condation', models.TextField(default=False)),
                ('cancellationPeriod', models.DurationField(default=datetime.timedelta(0))),
            ],
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_id', models.IntegerField(max_length=10)),
                ('airline_name', models.CharField(max_length=20)),
                ('description', models.TimeField(max_length=400)),
                ('policy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.policy')),
            ],
        ),
    ]
